export const prismicElements = {
  heading1:     'h1',
  heading2:     'h2',
  heading3:     'h3',
  heading4:     'h4',
  heading5:     'h5',
  heading6:     'h6',
  paragraph:    'p',
  preformatted: 'pre',
  strong:       'strong',
  em:           'em',
  listItem:     'li',
  oListItem:    'li',
  list:         'ul',
  oList:        'ol',
  image:        'img',
  embed:        'embed',
  hyperlink:    'a',
  label:        'span',
  span:         'span',
}