backend:
  name: github
  repo: alexeiaccio/moscowriver # Path to your Github repository
  branch: first-step # Branch to update (master by default)

media_folder: "static/img" # Folder where user uploaded files should go
public_folder: "/img"

collections: # A list of collections the CMS should be able to edit  
  - name: "pages"
    label: "Страницы"
    files:
      - file: "content/data/mainpage.md"
        label: "Главная"
        name: "mainpage"
        fields:
          - {label: Type, name: type, widget: hidden, default: data}
          - {label: To, name: to, widget: hidden, default: mainpage}
          - {label: Title, name: title, widget: string}
          - {label: "Заголовок №1", name: headingOne, widget: string}
          - {label: "Текст №1-1", name: descriptionOneOne, widget: string}
          - {label: "Текст №1-2", name: descriptionOneTwo, widget: string}
          - {label: "Заголовок №2", name: headingTwo, widget: string}
          - {label: "Текст №2", name: descriptionTwo, widget: string}
          - {label: "Заголовок №3", name: headingThree, widget: string}
          - {label: "Текст №3-1", name: descriptionThreeOne, widget: string}
          - {label: "Текст №3-2", name: descriptionThreeTwo, widget: string}
          - {label: "Заголовок №4", name: headingFour, widget: string}
          - {label: "Текст №4", name: descriptionFour, widget: string}
          - {label: "Заголовок №5", name: headingFive, widget: string}
          - {label: "Текст №5", name: descriptionFive, widget: string}
          - {label: "Заголовок формы", name: headingForm, widget: string}
          - {label: "Плейсхолдер формы", name: placholderForm, widget: string}
  - name: quotes
    label: "Цитаты"
    folder: "content/quotes"
    create: true
    fields:
      - {label: Type, name: type, widget: hidden, default: quotes}
      - {label: "Участок", name: sector, widget: string}
      - {label: "Набережная", name: embankment, widget: string} 
      - {label: "Вопрос", name: question, widget: string, required: false}
      - {label: "Ответ", name: body, widget: "markdown"}
      - {label: "Человек", name: human, widget: select, options: ["Child", "Woman", "Man", "Old Man", "Old Woman"]}