backend:
  name: github
  repo: alexeiaccio/moscowriver # Path to your Github repository
  branch: first-step # Branch to update (master by default)

media_folder: "static/img" # Folder where user uploaded files should go
public_folder: "/img"

collections: # A list of collections the CMS should be able to edit  
  - name: "pages"
    label: "Страницы"
    files:
      - file: "data/mainpage.md"
        label: "Главная"
        name: "mainpage"
        fields:
          - {label: Layout, name: layout, widget: hidden, default: index}
          - {label: Title, name: title, widget: string}
          - {label: Heading, name: heading, widget: string}
          - {label: Description, name: description, widget: string}