backend:
  name: github
  repo: alexeiaccio/moscowriver # Path to your Github repository
  branch: first-step # Branch to update (master by default)

media_folder: "static/img" # Folder where user uploaded files should go
public_folder: "/img"

collections: # A list of collections the CMS should be able to edit  
  - name: "pages"
    label: "Страницы"
    files:
      - file: "content/data/mainpage.md"
        label: "Главная"
        name: "mainpage"
        fields:
          - {label: Type, name: type, widget: hidden, default: data}
          - {label: To, name: to, widget: hidden, default: mainpage}
          - {label: Title, name: title, widget: string}
          - {label: Heading, name: heading, widget: string}
          - {label: Description, name: description, widget: string}
  - name: quotes
    label: "Цитаты"
    folder: "content/quotes"
    slug: "{{slug}}"
    create: true
    fields:
      - {label: Type, name: type, widget: hidden, default: quotes}
      - {label: "Участок", name: sector, widget: select, options: ["1.0", "2.0", "3.1", "3.2", "3.3"]}
      - {label: "Вопрос", name: question, widget: string, default: null}
      - {label: "Ответ", name: answer, widget: markdown}
      - {label: "Человек", name: human, widget: select, options: ["Child", "Woman", "Man", "Old Man", "Old Woman"]}
      - {label: "Возраст", name: "age", widget: "number", default: null}