backend:
  name: github
  repo: alexeiaccio/moscowriver # Path to your Github repository
  branch: first-step # Branch to update (master by default)

media_folder: "static/img" # Folder where user uploaded files should go
public_folder: "/img"

collections: # A list of collections the CMS should be able to edit  
  - name: "pages"
    label: "Страницы"
    files:
      - file: "content/data/mainpage.md"
        label: "Главная"
        name: "mainpage"
        fields:
          - {label: Type, name: type, widget: hidden, default: data}
          - {label: To, name: to, widget: hidden, default: mainpage}
          - {label: Title, name: title, widget: string}
          - {label: Heading, name: heading, widget: string}
          - {label: Description, name: description, widget: string}
  - name: quotes
    label: "Цитаты"
    folder: "content/quotes"
    create: true
    fields:
      - {label: Type, name: type, widget: hidden, default: quotes}
      - {label: "Участок", name: sector, widget: select, options: ["1", "2", "3.1", "3.2", "3.3", "4", "5", "6.1", "6.2", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16.1", "16.2", "17", "18.1", "18.2", "19", "20", "21", "22", "23", "24"]}
      - {label: "Набережная", name: embankment, widget: string} 
      - {label: "Вопрос", name: question, widget: string, required: false}
      - {label: "Ответ", name: body, widget: "markdown"}
      - {label: "Человек", name: human, widget: select, options: ["Child", "Woman", "Man", "Old Man", "Old Woman"]}